# Generated by Django 3.2.23 on 2023-11-24 15:25

from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.statuses


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0058_jobresult_add_time_status_idxs'),
        ('nautobot_design_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='status',
        ),
        migrations.AddField(
            model_name='designinstance',
            name='oper_status',
            field=nautobot.extras.models.statuses.StatusField(null=True, on_delete=django.db.models.deletion.PROTECT, to='extras.status'),
        ),
        migrations.AddField(
            model_name='designinstance',
            name='status',
            field=nautobot.extras.models.statuses.StatusField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nautobot_design_builder_designinstance_related', to='extras.status'),
        ),
        migrations.AlterField(
            model_name='designinstance',
            name='first_implemented',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='nautobot_design_builder.journal'),
        ),
    ]
