# Generated by Django 3.2.23 on 2024-01-03 06:22

from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.statuses


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0058_jobresult_add_time_status_idxs"),
        ("nautobot_design_builder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="design",
            name="status",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="_custom_field_data",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="tags",
        ),
        migrations.AddField(
            model_name="designinstance",
            name="live_state",
            field=nautobot.extras.models.statuses.StatusField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AddField(
            model_name="designinstance",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_design_builder_designinstance_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="designinstance",
            name="first_implemented",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="design_instance",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to="nautobot_design_builder.designinstance",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="nautobot_design_builder.journal",
            ),
        ),
    ]
