# Generated by Django 3.2.23 on 2024-01-02 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_design_builder', '0002_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='_custom_field_data',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='tags',
        ),
        migrations.AlterField(
            model_name='journal',
            name='design_instance',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='nautobot_design_builder.designinstance'),
        ),
    ]
