# Generated by Django 3.2.20 on 2024-04-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_design_builder', '0004_support_update_design'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designinstance',
            options={'verbose_name': 'Design Deployment', 'verbose_name_plural': 'Design Deployments'},
        ),
        migrations.RemoveField(
            model_name='designinstance',
            name='owner',
        ),
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='design',
            name='docs',
            field=models.CharField(blank=True, default='', editable=False, max_length=4096),
        ),
        migrations.AddField(
            model_name='design',
            name='version',
            field=models.CharField(default='0.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='designinstance',
            name='version',
            field=models.CharField(default='0.0.0', max_length=20),
            preserve_default=False,
        ),
    ]
