# Generated by Django 3.2.20 on 2024-04-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_design_builder", "0004_support_update_design"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="designinstance",
            options={"verbose_name": "Design Deployment", "verbose_name_plural": "Design Deployments"},
        ),
        migrations.RemoveField(
            model_name="designinstance",
            name="owner",
        ),
        migrations.AddField(
            model_name="designinstance",
            name="version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="designinstance",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
