# Generated by Django 3.2.20 on 2024-04-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_design_builder", "0004_support_update_design"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="version",
            field=models.CharField(default="0.0.1", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="designinstance",
            name="version",
            field=models.CharField(default="0.0.1", max_length=20),
            preserve_default=False,
        ),
    ]
