# Generated by Django 3.2.23 on 2024-01-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_design_builder', '0005_journal_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
