# Generated by Django 3.2.20 on 2024-04-08 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_design_builder", "0005_auto_20240405_0938"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designinstance",
            name="owner",
        ),
    ]
