# Generated by Django 3.2.20 on 2024-04-15 18:10

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.statuses


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0058_jobresult_add_time_status_idxs"),
        ("nautobot_design_builder", "0005_auto_20240415_0455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designinstance",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="design_instance_statuses",
                to="extras.status",
            ),
        ),
    ]
