# Generated by Django 3.2.20 on 2024-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_design_builder", "0006_alter_designinstance_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={"ordering": ["-last_updated"]},
        ),
        migrations.RemoveField(
            model_name="journal",
            name="builder_output",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
