# Generated by Django 3.2.20 on 2024-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_design_builder", "0006_remove_designinstance_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="description",
            field=models.CharField(default="Not defined", max_length=255),
            preserve_default=False,
        ),
    ]
